Explicitly build-require python3-wheel on XS9
Currently the build would fail, after running `dnf builddep` with:

 error: Failed build dependencies:
	python3dist(wheel) is needed by xcp-python-libs-3.0.4-1.1.xcpng8.99.noarch